spring.application.name=loan-management-system

#database config
spring.datasource.url=jdbc:postgresql://localhost:5432/loan
spring.datasource.username=postgres
spring.datasource.password=123456

#hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.address=0.0.0.0
server.port=8081

fin.service.base-url=http://ec2-34-200-233-130.compute-1.amazonaws.com:8081
fin.service.auth.register-endpoint=/api/auth/register
fin.service.auth.login-endpoint=/api/auth/login

jwt.secret=8fK9!dPq3#M2Z@R6Lx7B0aN$YHcE4WJvS1U
jwt.expiration=3600000